name: Deploy to Another Repo

on:
  workflow_dispatch: # 仅允许手动触发

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - name: Install Dependencies
        run: yarn install
      - name: Build Project
        run: npm run build
      - name: Deploy to target repo
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: git@github.com:PiuQiuPiaQia/letsread.github.io.git
          BRANCH: main
          FOLDER: dist
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
